### ISSUE TITLE
Is it possible to make this project live on npm?

### ISSUE THREAD

**Issue by LiangNex** [ustbhuangyi/vue-picker#1]
Vote for this project 👍 (Though it's possibly late after 2 years 🤕 )
I am currently integrating the relative code, just wondering if it's possible to make it live on [npm](https://www.npmjs.com/)

**Comment by ustbhuangyi** [comment]
@LiangNex Maybe u can partly use the picker component of cube-ui, it's maintained by a very professional team. See the doc here: https://didi.github.io/cube-ui/#/en-US/docs/picker

**Comment by LiangNex** [comment]
👍 great, thanks a lot
